import { defaultSchema, type Options } from 'rehype-sanitize';

/* One allowlist shared by the build and the editor preview. Anything not here is stripped.
   Shiki output needs `style` on spans and `class`/data attrs on pre/code; images need alt and dimensions. */
export const sanitizeSchema: Options = {
  ...defaultSchema,
  // Heading ids are generated by rehype-slug and used for in-page links; no clobber prefix.
  clobberPrefix: '',
  tagNames: [...(defaultSchema.tagNames ?? []), 'figure', 'figcaption', 'picture', 'source'],
  attributes: {
    ...defaultSchema.attributes,
    '*': [...(defaultSchema.attributes?.['*'] ?? []), 'className', 'id'],
    pre: ['className', 'style', 'tabIndex', ['dataLanguage']],
    code: ['className', 'style'],
    span: ['className', 'style'],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading', 'decoding'],
    source: ['srcSet', 'type', 'sizes'],
    a: ['href', 'title', 'rel', 'target'],
    input: ['type', 'checked', 'disabled', 'ariaLabel'],
  },
  protocols: { ...defaultSchema.protocols, src: ['http', 'https', 'data'] },
};
