/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as EditorSlugRouteImport } from './routes/editor.$slug'
import { Route as EditorNewRouteImport } from './routes/editor.new'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorSlugRoute = EditorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EditorRoute,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EditorRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/editor': typeof EditorRouteWithChildren
  '/home': typeof HomeRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
  '/login/callback': typeof LoginCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/editor/': typeof EditorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/home': typeof HomeRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
  '/login/callback': typeof LoginCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/editor': typeof EditorIndexRoute
  '/login': typeof LoginIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/editor': typeof EditorRouteWithChildren
  '/home': typeof HomeRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
  '/login/callback': typeof LoginCallbackRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/editor/': typeof EditorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/editor'
    | '/home'
    | '/editor/$slug'
    | '/editor/new'
    | '/login/callback'
    | '/posts/$slug'
    | '/editor/'
    | '/login/'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/home'
    | '/editor/$slug'
    | '/editor/new'
    | '/login/callback'
    | '/posts/$slug'
    | '/editor'
    | '/login'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/editor'
    | '/home'
    | '/editor/$slug'
    | '/editor/new'
    | '/login/callback'
    | '/posts/$slug'
    | '/editor/'
    | '/login/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  EditorRoute: typeof EditorRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  PostsSlugRoute: typeof PostsSlugRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$slug': {
      id: '/editor/$slug'
      path: '/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof EditorSlugRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof EditorRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditorRouteChildren {
  EditorSlugRoute: typeof EditorSlugRoute
  EditorNewRoute: typeof EditorNewRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorSlugRoute: EditorSlugRoute,
  EditorNewRoute: EditorNewRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  EditorRoute: EditorRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  PostsSlugRoute: PostsSlugRoute,
  LoginIndexRoute: LoginIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
