/* The only place @mdi/js is imported. Add an icon here, never inline. */
export {
  mdiArrowDown,
  mdiArrowUp,
  mdiBrightnessAuto,
  mdiChevronDoubleDown,
  mdiChevronDoubleUp,
  mdiCodeBraces,
  mdiCodeTags,
  mdiDotsVertical,
  mdiDragVertical,
  mdiFileDocumentOutline,
  mdiFormatBold,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatQuoteClose,
  mdiFormatStrikethrough,
  mdiGithub,
  mdiImagePlus,
  mdiLinkedin,
  mdiLinkVariant,
  mdiMinus,
  mdiMoonWaningCrescent,
  mdiNpm,
  mdiOpenInNew,
  mdiPencil,
  mdiSchoolOutline,
  mdiSourceBranch,
  mdiStackOverflow,
  mdiTwitter,
  mdiWhiteBalanceSunny,
} from "@mdi/js";
